// AUTO-GENERATED by scripts/yc-audit-study.ts alongside yc-study.ts.
// Client-safe subset: scalars only, no per-company rows.

export const YC_STUDY_SUMMARY = {
  "ranAt": "2026-09-12",
  "audited": 494,
  "median": 75,
  "topName": "Avoca Systems",
  "topScore": 98
} as const;
