// AUTO-GENERATED by scripts/yc-audit-study.ts alongside yc-study.ts.
// Client-safe subset: scalars only, no per-company rows.

export const YC_STUDY_SUMMARY = {
  "ranAt": "2026-09-07",
  "audited": 496,
  "median": 71,
  "topName": "Didit",
  "topScore": 94
} as const;
